//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/cat/csw/2.0.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.opengis.net/cat/csw/2.0.2", IsNullable=false)]
public partial class GetRecordsResponse {
    
    private GetRecordsResponseSearchStatus[] searchStatusField;
    
    private GetRecordsResponseSearchResults[] searchResultsField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SearchStatus")]
    public GetRecordsResponseSearchStatus[] SearchStatus {
        get {
            return this.searchStatusField;
        }
        set {
            this.searchStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SearchResults")]
    public GetRecordsResponseSearchResults[] SearchResults {
        get {
            return this.searchResultsField;
        }
        set {
            this.searchResultsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/cat/csw/2.0.2")]
public partial class GetRecordsResponseSearchStatus {
    
    private string timestampField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string timestamp {
        get {
            return this.timestampField;
        }
        set {
            this.timestampField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/cat/csw/2.0.2")]
public partial class GetRecordsResponseSearchResults {
    
    private MCRasterRecord[] mCRasterRecordField;
    
    private string elementSetField;
    
    private string nextRecordField;
    
    private string numberOfRecordsMatchedField;
    
    private string numberOfRecordsReturnedField;
    
    private string recordSchemaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MCRasterRecord", Namespace="http://schema.mapcolonies.com/raster")]
    public MCRasterRecord[] MCRasterRecord {
        get {
            return this.mCRasterRecordField;
        }
        set {
            this.mCRasterRecordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string elementSet {
        get {
            return this.elementSetField;
        }
        set {
            this.elementSetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nextRecord {
        get {
            return this.nextRecordField;
        }
        set {
            this.nextRecordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string numberOfRecordsMatched {
        get {
            return this.numberOfRecordsMatchedField;
        }
        set {
            this.numberOfRecordsMatchedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string numberOfRecordsReturned {
        get {
            return this.numberOfRecordsReturnedField;
        }
        set {
            this.numberOfRecordsReturnedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string recordSchema {
        get {
            return this.recordSchemaField;
        }
        set {
            this.recordSchemaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schema.mapcolonies.com/raster")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schema.mapcolonies.com/raster", IsNullable=false)]
public partial class MCRasterRecord {
    
    private string classificationField;
    
    private string creationDateUTCField;
    
    private string descriptionField;
    
    private string footprintField;
    
    private string idField;
    
    private string ingestionDateField;
    
    private string insertDateField;
    
    private string maxResolutionDegField;
    
    private string maxResolutionMeterField;
    
    private string minHorizontalAccuracyCE90Field;
    
    private string producerNameField;
    
    private string productBBoxField;
    
    private string productIdField;
    
    private string productNameField;
    
    private string productSubTypeField;
    
    private string productTypeField;
    
    private string productVersionField;
    
    private string regionField;
    
    private string rMSField;
    
    private string scaleField;
    
    private string sensorsField;
    
    private string imagingTimeEndUTCField;
    
    private string imagingTimeBeginUTCField;
    
    private string sRSField;
    
    private string sRSNameField;
    
    private string mimeTypeField;
    
    private string transparencyField;
    
    private string typeField;
    
    private string updateDateUTCField;
    
    private MCRasterRecordLinks[] linksField;
    
    private BoundingBox boundingBoxField;
    
    /// <remarks/>
    public string classification {
        get {
            return this.classificationField;
        }
        set {
            this.classificationField = value;
        }
    }
    
    /// <remarks/>
    public string creationDateUTC {
        get {
            return this.creationDateUTCField;
        }
        set {
            this.creationDateUTCField = value;
        }
    }
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string footprint {
        get {
            return this.footprintField;
        }
        set {
            this.footprintField = value;
        }
    }
    
    /// <remarks/>
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string ingestionDate {
        get {
            return this.ingestionDateField;
        }
        set {
            this.ingestionDateField = value;
        }
    }
    
    /// <remarks/>
    public string insertDate {
        get {
            return this.insertDateField;
        }
        set {
            this.insertDateField = value;
        }
    }
    
    /// <remarks/>
    public string maxResolutionDeg {
        get {
            return this.maxResolutionDegField;
        }
        set {
            this.maxResolutionDegField = value;
        }
    }
    
    /// <remarks/>
    public string maxResolutionMeter {
        get {
            return this.maxResolutionMeterField;
        }
        set {
            this.maxResolutionMeterField = value;
        }
    }
    
    /// <remarks/>
    public string minHorizontalAccuracyCE90 {
        get {
            return this.minHorizontalAccuracyCE90Field;
        }
        set {
            this.minHorizontalAccuracyCE90Field = value;
        }
    }
    
    /// <remarks/>
    public string producerName {
        get {
            return this.producerNameField;
        }
        set {
            this.producerNameField = value;
        }
    }
    
    /// <remarks/>
    public string productBBox {
        get {
            return this.productBBoxField;
        }
        set {
            this.productBBoxField = value;
        }
    }
    
    /// <remarks/>
    public string productId {
        get {
            return this.productIdField;
        }
        set {
            this.productIdField = value;
        }
    }
    
    /// <remarks/>
    public string productName {
        get {
            return this.productNameField;
        }
        set {
            this.productNameField = value;
        }
    }
    
    /// <remarks/>
    public string productSubType {
        get {
            return this.productSubTypeField;
        }
        set {
            this.productSubTypeField = value;
        }
    }
    
    /// <remarks/>
    public string productType {
        get {
            return this.productTypeField;
        }
        set {
            this.productTypeField = value;
        }
    }
    
    /// <remarks/>
    public string productVersion {
        get {
            return this.productVersionField;
        }
        set {
            this.productVersionField = value;
        }
    }
    
    /// <remarks/>
    public string region {
        get {
            return this.regionField;
        }
        set {
            this.regionField = value;
        }
    }
    
    /// <remarks/>
    public string RMS {
        get {
            return this.rMSField;
        }
        set {
            this.rMSField = value;
        }
    }
    
    /// <remarks/>
    public string scale {
        get {
            return this.scaleField;
        }
        set {
            this.scaleField = value;
        }
    }
    
    /// <remarks/>
    public string sensors {
        get {
            return this.sensorsField;
        }
        set {
            this.sensorsField = value;
        }
    }
    
    /// <remarks/>
    public string imagingTimeEndUTC {
        get {
            return this.imagingTimeEndUTCField;
        }
        set {
            this.imagingTimeEndUTCField = value;
        }
    }
    
    /// <remarks/>
    public string imagingTimeBeginUTC {
        get {
            return this.imagingTimeBeginUTCField;
        }
        set {
            this.imagingTimeBeginUTCField = value;
        }
    }
    
    /// <remarks/>
    public string SRS {
        get {
            return this.sRSField;
        }
        set {
            this.sRSField = value;
        }
    }
    
    /// <remarks/>
    public string SRSName {
        get {
            return this.sRSNameField;
        }
        set {
            this.sRSNameField = value;
        }
    }
    
    /// <remarks/>
    public string mimeType {
        get {
            return this.mimeTypeField;
        }
        set {
            this.mimeTypeField = value;
        }
    }
    
    /// <remarks/>
    public string transparency {
        get {
            return this.transparencyField;
        }
        set {
            this.transparencyField = value;
        }
    }
    
    /// <remarks/>
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string updateDateUTC {
        get {
            return this.updateDateUTCField;
        }
        set {
            this.updateDateUTCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("links", IsNullable=true)]
    public MCRasterRecordLinks[] links {
        get {
            return this.linksField;
        }
        set {
            this.linksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.opengis.net/ows")]
    public BoundingBox BoundingBox {
        get {
            return this.boundingBoxField;
        }
        set {
            this.boundingBoxField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schema.mapcolonies.com/raster")]
public partial class MCRasterRecordLinks {
    
    private string descriptionField;
    
    private string nameField;
    
    private string schemeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string scheme {
        get {
            return this.schemeField;
        }
        set {
            this.schemeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/ows")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.opengis.net/ows", IsNullable=false)]
public partial class BoundingBox {
    
    private string lowerCornerField;
    
    private string upperCornerField;
    
    private string crsField;
    
    private string dimensionsField;
    
    /// <remarks/>
    public string LowerCorner {
        get {
            return this.lowerCornerField;
        }
        set {
            this.lowerCornerField = value;
        }
    }
    
    /// <remarks/>
    public string UpperCorner {
        get {
            return this.upperCornerField;
        }
        set {
            this.upperCornerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string crs {
        get {
            return this.crsField;
        }
        set {
            this.crsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dimensions {
        get {
            return this.dimensionsField;
        }
        set {
            this.dimensionsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.opengis.net/cat/csw/2.0.2")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.opengis.net/cat/csw/2.0.2", IsNullable=false)]
public partial class NewDataSet {
    
    private GetRecordsResponse[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GetRecordsResponse")]
    public GetRecordsResponse[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
